#!/usr/bin/env bash
# Configure the server to listen on port 80 of all server's active IPv4 ips
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
