#!/usr/bin/env bash
# Configure the server to listen on port 80 of all server's active IPv4 IPs

# Check if the Nginx configuration file exists
if [ -f "/etc/nginx/sites-available/default" ]; then
	# Modify the configuration file to listen on port 80
	sudo sed -i "s/8080/80/" /etc/nginx/sites-available/default

	# Restart the Nginx service
	sudo service nginx restart
else
	echo "Nginx configuration file not found"
fi
