#!/usr/bin/env bash
# Manages the script manage_my_process.

case "$1" in
    start)
        /tmp/manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat /var/run/my_process.pid)"
        echo "manage_my_process stopped"
        ;;
    restart)
        kill "$(cat /var/run/my_process.pid)"
        /tmp/manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
