#!/usr/bin/env bash
# Read the file /etc/passwd line by line
while IFS=':' read -r username x uid gid info home shell; do
    # Print username, user id, and home directory path for each user
    echo "$username:$uid:$home"
done </etc/passwd
