#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.

while IFS=':' read -r username x uid gid info home shell; do
    # Print username, user id, and home directory path for each user
    echo "$username:$uid:$home"
done </etc/passwd
